INSERT INTO department (dept_name)
VALUES ('Customer Service'),
       ('Finance'),
       ('Human Resources'),
       ('IT'),
       ('Marketing'),
       ('Operations'),
       ('Sales'),
       ('Executive');

INSERT INTO role (title, salary, dept_id)
VALUES ('Director of Customer Experience', '78,500', 1),
       ('Customer Service Manager', '48,500', 1 ),
       ('Customer Service Rep', '37,500', 1 ),
       ('Finance Director', '85,500', 2),
       ('Accountant', '66,500', 2 ),
       ('Finance Specialist', '52,500', 2),
       ('HR Director', '77,500', 3),
       ('HR Recruiter', '57,500', 3),
       ('IT Director', '84,500', 4),
       ('Cloud Architect', '73,500', 4),
       ('Security Engineer', '72,500', 4),
       ('System Administrator', '70,500', 4),
       ('Marketing Director', '79,500', 5),
       ('Market Research Analyst', '68,500', 5),
       ('Operations Director', '77,500', 6),
       ('Operations Manager', '68,500', 6),
       ('Data Analyst', '63,500', 6),
       ('Sales Director', '81,500', 7),
       ('Sales Development Representative', '44,500', 7),
       ('Account Manager', '55,500', 7),
       ('Cheif Executive Officer', '145,500', 8);

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ('Dorian','Young', 1, 21),
       ('Robert','Porter', 2, 1 ),
       ('Angela','Chang', 3, 2 ),
       ('Kimberly','Baxter', 4, 21),
       ('Brittany','Harris', 5, 4 ),
       ('Teresa','Nichols', 6, 4),
       ('Juan','Alverez', 7, 21),
       ('Elana','Scott', 8, 7),
       ('Kayleigh','Carter', 9, 21),
       ('Royce','Richmond', 10, 9),
       ('Nancy','Franklin', 11, 9),
       ('Bianca','Vazquez', 12, 9),
       ('Kylie','Vincent', 13, 21),
       ('Desmond','McDougald', 14, 13),
       ('Isabella','Tanner', 15, 21),
       ('Thomas','Sullivan', 16, 15),
       ('Cornell','Burke', 17, 15),
       ('Christina','Gunter', 18, 21),
       ('Peter','Delgado', 19, 18),
       ('Justice','Graham', 20, 18),
       ('Blake','Fitzpatrick', 21,NULL);